# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI

on:
  push:
    branches: [ main, uat, prod ]
  pull_request:
    branches: [ main, uat, prod ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build,  test
      run: |
        npm ci
        npm run test
        npm run build
    - name: Runner workspace path
      run: |
        echo "Cleaning up previous run"
        echo ${{ github.workspace }}
        rm -rf "${{ github.workspace }}"
